# Generated by Django 4.1.2 on 2022-11-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.FloatField(),
        ),
    ]
