# Generated by Django 4.1.2 on 2022-11-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_image_remove_place_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='imgs',
            field=models.TextField(blank=True),
        ),
    ]
