# Generated by Django 4.1.2 on 2022-11-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_remove_place_imgs_image_number_img_image_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='number_img',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
